=== eurolinux-enterprise-linux-sources/xml-stylebook/src/src/org/apache/stylebook/data/engine.dtd
<?xml encoding='US-ASCII'?>

<!-- ENGINE DTD: Specifies how the engine configuration file should
                 be formatted. Reference it as
                 SYSTEM "res:/org/apache/stylebook/data/engine.dtd" -->

<!-- engine: the root element of the configuration file -->
<!ELEMENT engine (debug?, parser, producer*, processor*, printer*)>

<!-- debug: enable or disable output of debug information -->
<!ELEMENT debug EMPTY>
<!ATTLIST debug enabled (true|false) "false">

<!-- parser: define the parser class used by stylebook -->
<!ELEMENT parser (parameter)*>
<!ATTLIST parser class CDATA #REQUIRED>

<!-- producer: associate a class with a producer name -->
<!ELEMENT producer (parameter)*>
<!ATTLIST producer name  CDATA #REQUIRED
                   class CDATA #REQUIRED>

<!-- processor: associate a class with a processor name -->
<!ELEMENT processor (parameter)*>
<!ATTLIST processor name  CDATA #REQUIRED
                    class CDATA #REQUIRED>

<!-- printer: associate a class with a printer name -->
<!ELEMENT printer (parameter)*>
<!ATTLIST printer name  CDATA #REQUIRED
                  class CDATA #REQUIRED>

<!-- parameter: a parameter passed to a class during initialiation -->
<!ELEMENT parameter EMPTY>
<!ATTLIST parameter name  CDATA #REQUIRED
                    value CDATA #REQUIRED>

<!-- CVS $Revision: 313209 $ $Date: 1999-12-01 13:52:36 +0100 (Wed, 01 Dec 1999) $ -->

=== eurolinux-enterprise-linux-sources/xml-stylebook/src/src/org/apache/stylebook/data/engine.xml
<?xml version="1.0"?>
<!DOCTYPE engine SYSTEM "res:/org/apache/stylebook/data/engine.dtd">

<!-- ENGINE CONFIGURATION: Configuration for the StyleBook Engine class.
                           See "engine.dtd" for informations. -->

<engine>

  <debug enabled="false"/>

  <parser class="org.apache.stylebook.parsers.CachingParser">
    <parameter name="parserclass" value="org.apache.stylebook.parsers.XercesParser"/>
    <parameter name="cachesize" value="10"/>
  </parser>

  <producer name="parser" class="org.apache.stylebook.producers.ParserProducer"/>
  <producer name="context" class="org.apache.stylebook.producers.ContextProducer"/>
  <producer name="project" class="org.apache.stylebook.producers.ProjectProducer"/>
  <producer name="directory" class="org.apache.stylebook.producers.DirectoryProducer"/>

  <processor name="null" class="org.apache.stylebook.processors.NullProcessor"/>
  <processor name="xslt" class="org.apache.stylebook.processors.XalanProcessor"/>
  <processor name="import" class="org.apache.stylebook.processors.ImportProcessor"/>

  <printer name="xml" class="org.apache.stylebook.printers.XMLPrinter"/>
  <printer name="html" class="org.apache.stylebook.printers.HTMLPrinter"/>
  <printer name="image" class="org.apache.stylebook.printers.ImagePrinter"/>

</engine>

<!-- CVS $Revision: 313220 $ $Date: 1999-12-01 19:38:23 +0100 (Wed, 01 Dec 1999) $ -->
