=== eurolinux-enterprise-linux-sources/xml-stylebook/src/styles/christmas/dtd/book.dtd
<?xml encoding='US-ASCII'?>

<!-- STYLEBOOK BOOK DTD -->

<!-- import the external source-specific dtd -->
<!ENTITY % externalEntity SYSTEM "sbk:/sources/entities.ent">
%externalEntity;

<!ELEMENT book (document|hidden|faqs|changes|group|external|separator)+>
<!ATTLIST book title     CDATA #REQUIRED
               copyright CDATA #IMPLIED>
               

<!ELEMENT document EMPTY>
<!ATTLIST document id     ID    #REQUIRED
                   source CDATA #REQUIRED
                   label  CDATA #REQUIRED>

<!ELEMENT hidden EMPTY>
<!ATTLIST hidden id     ID    #REQUIRED
                 source CDATA #REQUIRED>

<!ELEMENT faqs EMPTY>
<!ATTLIST faqs id     ID    #REQUIRED
               source CDATA #REQUIRED
               label  CDATA #REQUIRED>

<!ELEMENT changes EMPTY>
<!ATTLIST changes id     ID    #REQUIRED
                  source CDATA #REQUIRED
                  label  CDATA #REQUIRED>

<!ELEMENT group (entry)+>
<!ATTLIST group id    ID    #IMPLIED
                label CDATA #REQUIRED>

<!ELEMENT entry EMPTY>
<!ATTLIST entry id     ID    #REQUIRED
                source CDATA #REQUIRED>

<!ELEMENT external EMPTY>
<!ATTLIST external label CDATA #REQUIRED
                   href  CDATA #REQUIRED>
                   
<!ELEMENT separator EMPTY>

<!-- CVS $Revision: 313243 $ $Date: 1999-12-25 09:29:50 +0100 (Sat, 25 Dec 1999) $ -->

=== eurolinux-enterprise-linux-sources/xml-stylebook/src/docs/book.xml
<?xml version="1.0"?>
<!DOCTYPE book SYSTEM "sbk:/style/dtd/book.dtd">

<book title="Test Documentation" copyright="1999 Apache Software Foundation">
  <document id="readme"     label="Readme"     source="readme.xml"    />
  <document id="sections"   label="Sections"   source="sections.xml"  />
  <separator                                                          />
  <document id="blocks"     label="Blocks"     source="blocks.xml"    />
  <document id="characters" label="Characters" source="characters.xml"/>
  <document id="links"      label="Links"      source="links.xml"     />
  <separator                                                          />
  <faqs     id="faqs"       label="FAQ File"   source="faqs.xml"      />
  <group    id="faqgroup"   label="FAQ Group"                          >
    <entry  id="faqs-1"                        source="faqs-1.xml"    />
    <entry  id="faqs-2"                        source="faqs-2.xml"    />
  </group                                                              >    
  <changes  id="changes"    label="Changes"    source="changes.xml"   />
</book>
